// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = angular.module('demo', ['chart']);
  app.controller('DemoCtrl', [
    '$scope', function($scope) {
      return $scope.chartData = {
        Cake: 12,
        Pizza: 12,
        Burgers: 8,
        'Hot Dogs': 10
      };
    }
  ]);
  return app.value(name + '.config', {
    piechart: {
      title: 'Pie Chart'
    }
  });
})();
