// Generated by CoffeeScript 1.6.2
var app;

app = angular.module('gauge', ['chart']);

app.controller('GaugeCtrl', [
  '$scope', function($scope) {
    $scope.revs = 1500;
    return $scope.mph = 30;
  }
]);

app.value('chart.config', {
  gauge: {
    animation: {
      duration: 300,
      easing: 'in'
    }
  }
});
