// Generated by CoffeeScript 1.6.2
var app;

app = angular.module('piechart', ['chart']);

app.controller('PieChartCtrl', [
  '$scope', function($scope) {
    return $scope.chartData = {
      'Cake': 12,
      'Pizza': 12,
      'Burgers': 8,
      'Hot Dogs': 10
    };
  }
]);

app.value('chart.config', {
  piechart: {
    title: 'Pie Chart'
  }
});
